### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by afonsopacifer** [afonsopacifer/microscope#1]
# Cool things to do :)
- [x] Organize the versioning.
- [ ] Create a Yeoman generator.
- [ ]  Create grunt task for css tests.
- [ ] Add a functionality to see the HTML in the style guide.
- [ ] Isolate the components style (Shadow dom?).
- [ ] Responsive update in Style Guide.
- [ ] Add spacing pattern in global components.
- [ ] Improve the way of adding fonts.

**Note:** If you want to help, create an issue about what you want to do ;)
